spring.datasource.url=jdbc:mysql://localhost:3306/ngo_events
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=VUL_HIER_JE_MAILTRAP_USERNAME_IN
spring.mail.password=VUL_HIER_JE_MAILTRAP_PASSWORD_IN
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true